### ISSUE TITLE
Same extension as one on Chrome web store?

### ISSUE THREAD

**Issue by johnnystruck** [Microsoft/FMLab#14]
Hello,

I just want to avoid any confusion but is the FMLab MSD365 extension the same as the one offered on the Chrome web store found here: [D365 for Finance and Operations Task Recorder](https://chrome.google.com/webstore/detail/d365-for-finance-and-oper/inifapcodikhojbnbafaalgbgkfmnlob) ?

I ask simply because their documentation links to the MS official documentation and the website links to this repository. However the extension is "Offered by: Wazzarama." Does not seem official to me. Figured any extension developer can link to any website they wish.

Thank you,

Johnny

**Comment by FunctionalConsultantsthatCode** [comment]
Hello Johnny,
If you read the official documentation and get to this point 
https://docs.microsoft.com/en-us/dynamics365/unified-operations/dev-itpro/user-interface/task-recorder?toc=dynamics365/unified-operations/fin-and-ops/toc.json#screenshot-extension-setup
then actually try and do it and then roll it out to users. Most corporate environments will block loading unpacked extensions in chrome. 
I used the microsoft code as a base, then had to modify it a bit to comply with Chrome Web Extension standards,
While no one at microsoft gave me a official response as to why, my best guess is some MS developer had to do it to make a customer happy as they could do screenshots in Ax 2012, then couldn't be bothered publishing to the Chrome Web store, as it costs $5 and a lot of MS corporate red tape.

Wazzarama

**Comment by johnnystruck** [comment]
Hello Wazz,

Thank you for the thorough explanation- I was able to successfully use the MS official one, no need to roll out the extension to users (yet). I will try out your extension on a private deployment of D365.

Thanks,

Johnny
