### ISSUE TITLE
Chrome 57.0.2987 will create blank screenshots

### ISSUE THREAD

**Issue by rbogithub** [Microsoft/FMLab#6]
Hi, 

tried to use the "TaskRecorderScreenshot", enabling screen-shots when using D365fO & Chrome. I found that using version 57.0.2987 will create "blank" screen-shots when exporting to WORD. I downgraded chrome back to version 56.0.2924 and works perfectly. Anyone being able to fix this? or will this project not have any updates? Appreciate your feedback

**Comment by syed-adnan** [comment]
Hi,
This issue is now fixed in the latest version of the plugin.

Regards,

Adnan
